version: "3.8"

services:
    e2m:
        build: .
        command: ["gunicorn", "--bind", "0.0.0.0:8765", "app:create_app()"]
        ports:
            - "8765:8765"
        volumes:
            - .:/app
        environment:
            FLASK_APP: app.py
            FLASK_ENV: production
