version: '3.8'

services:
  e2m:
    build: .
    command: flask run --host=0.0.0.0 --port=8765
    ports:
      - "8765:8765"
    volumes:
      - .:/app
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development
