__version__ = "v1.1.3"
__email__ = "yilin.jing.ai@outlook.com"
__description__ = "E2M (Everything to Markdown) API Service"
__github__ = "https://github.com/Jing-yilin/E2M"
__docker__ = "https://hub.docker.com/r/jingyilin/e2m/tags"
