from api.core.llms.prompts.prompts import (
    OCR_FIX_TO_MARKDOWN_PROMPT,
    OCR_FIX_TO_JSON_PROMPT,
    EXTRACT_MARKDOWN_PROMPT,
    EXTRACT_JSON_PROMPT,
    ADDITIONAL_PROMTPT,
)


__all__ = [
    "OCR_FIX_TO_MARKDOWN_PROMPT",
    "OCR_FIX_TO_JSON_PROMPT",
    "EXTRACT_MARKDOWN_PROMPT",
    "EXTRACT_JSON_PROMPT",
    "ADDITIONAL_PROMTPT",
]
