OCR_FIX_TO_MARKDOWN_PROMPT = """Please correct the following OCR-recognized text and convert it to Markdown format:
```
{ocr_text}
```
When making corrections and converting to Markdown, please follow these guidelines:

1. Fix OCR errors to make the text smooth and easily understandable.
2. Preserve the original paragraph structure and overall document organization.
3. Use appropriate Markdown syntax for titles, lists, and other elements.
4. Remove any irrelevant characters or garbled text generated by OCR.
5. If the text contains image URLs, embed them using Markdown syntax.
6. For mathematical formulas, use LaTeX syntax within Markdown. For code snippets, use appropriate Markdown code block syntax.
7. Use the same language as the OCR text (e.g., if the OCR text is in Chinese, the corrected text should also be in Chinese).
8. Maintain the accuracy of professional terms and domain-specific vocabulary.
9. Ensure proper formatting for any tables or structured data in the text.
10. If the end of the text is cut off, do not add any new characters or `...` beyond the last recognized character.

Please output the corrected and formatted Markdown text in a code block, starting with the table of contents.

Example output:
```markdown
# Section 1
Content of section 1...

## Subsection 1.1
Content of subsection 1.1...

# Section 2
Content of section 2...

[Embedded image](image_url.jpg)

Mathematical formula: $E = mc^2$

```code
print("Hello, World!")
```
```

Remember, this is the first part of the document, so focus on establishing a clear structure and formatting that can be continued in subsequent parts.
"""


# ocr_text, pre_toc, pre_overlap, overlap
BLOCK_OCR_FIX_TO_MARKDOWN_PROMPT = """Please correct and convert the following OCR-recognized text to Markdown format, ensuring seamless integration with the previous content:

Previous content (last {overlap} characters):
```
{pre_overlap}
```

Current OCR text to process:
```
{ocr_text}
```

Previous Table of Contents:
```
{pre_toc}
```

When making corrections and converting to Markdown, please adhere to these guidelines:

1. Ensure smooth continuation from the previous content. Start exactly where the previous section ended.
2. Maintain consistent formatting and style with the previous content.
3. Continue any incomplete sentences or thoughts from the end of the previous section.
4. Use appropriate Markdown syntax for titles, lists, and other elements. Ensure heading levels are consistent with the overall document structure.
5. Fix OCR errors to make the text smooth and easily understandable.
6. Remove any irrelevant characters or garbled text generated by OCR.
7. For image URLs, use proper Markdown embedding syntax.
8. Use LaTeX syntax within Markdown for mathematical formulas. For code snippets, use appropriate Markdown code block syntax.
9. Use the same language as the OCR text (e.g., if the OCR text is in Chinese, the corrected text should also be in Chinese).
10. Maintain the accuracy of professional terms and domain-specific vocabulary.
11. If dealing with content split across pages, ensure proper connection and flow.
12. Do not repeat any content from the previous overlap.
13. If the end of the text is cut off, do not add any new characters or `...` beyond the last recognized character.

Please output the corrected and formatted Markdown text in a code block. The output should start precisely where the previous content ended, ensuring a seamless continuation of the document.

Example output:
```markdown
...content that can be continued from the previous section...

## New Section (if applicable)
Content of the new section...

### Subsection
More content...

[Embedded image](image_url.jpg)

Mathematical formula: $E = mc^2$

```code
print("Hello, World!")
```
```

Remember, the goal is to produce a section that can be directly appended to the previous content without any manual adjustments, forming a cohesive and complete document.
"""

OCR_FIX_TO_JSON_PROMPT = """Please correct the following OCR-recognized text and output the result in JSON format:
```
{ocr_text}
```

User-enforced JSON Format:
```
{enforced_json_format}
```
When making corrections, please adhere to these guidelines:
1. Correct misrecognized words and phrases to improve readability and comprehension
2. Maintain the original paragraph structure and line breaks
3. Identify and extract key information such as titles, headings, lists, names, dates, and numbers
4. Remove irrelevant characters, symbols, and garbled text introduced by OCR recognition errors
5. If user-enforced JSON format is provided, ensure that the corrected text is formatted accordingly
6. You should use language that is corresponding to the ocr text, for example, if the ocr text is in Chinese, the corrected text should also be in Chinese.

Finally, please output the corrected JSON text in a code block.

Example:
```
{{
  "key": "value",
  "key2": "value2"
}}
```"""

EXTRACT_MARKDOWN_PROMPT = """Please analyze the provided image and extract the content in Markdown format. The image will contain text, headings, lists, tables, and possibly code snippets.
When extracting the content, please adhere to the following guidelines:
1. Identify and extract text, preserving the original formatting and structure as much as possible
2. Detect and properly format headings (H1, H2, H3, etc.) using Markdown syntax
3. Recognize and format lists (ordered and unordered) using Markdown syntax
4. Identify and format tables using Markdown syntax, preserving the table structure and content
5. Detect and format any code snippets using Markdown code blocks, preserving the code's syntax and indentation
6. For mathematical formulas or equations, use appropriate Markdown syntax to maintain readability
7. If the image contains any inline images or diagrams, describe them using alt text in Markdown format
8. Preserve the original line breaks and paragraph structure to maintain readability

Finally, please output the extracted content in Markdown format within a code block.

Example:
```
# Title
This is a list:
- Item 1
- Item 2
```"""

EXTRACT_JSON_PROMPT = """Please analyze the image and extract the content in JSON format. The image may contain structured data, key-value pairs, lists, or other JSON-compatible content.
When extracting the content, please adhere to the following guidelines:
1. Identify and extract structured data, key-value pairs, lists, or other JSON-compatible content
2. Maintain the original structure and hierarchy of the extracted data
3. Correct any misrecognized words or phrases to ensure the extracted JSON is accurate
4. Remove any irrelevant characters, symbols, or garbled text introduced by OCR recognition errors
5. If the image contains nested data structures, represent them accurately in the extracted JSON format
6. You should use language that is corresponding to the ocr text, for example, if the ocr text is in English, the extracted JSON should also be in English.

Finally, please output the extracted content in JSON format within a code block.

Example:
```
{{
  "key": "value",
  "key2": "value2"
}}
```"""


COMMENT_PROMTPT = """You should also follow the instruction to complete the task:
{comment}
"""
