OCR_FIX_TO_MARKDOWN_PROMPT = """Please correct the following OCR-recognized text to make it easy to read and output it in Markdown format:
```
{ocr_text}
```
When making corrections, please keep the following points in mind:
1. Fix incorrectly recognized words to make the text smooth and easy to understand
2. Preserve the original paragraph structure
3. Identify titles, lists, and other elements, and mark them using Markdown syntax
4. Remove irrelevant characters and garbled text generated by OCR recognition
5. If the text contains image URLs, embed them using Markdown syntax
6. You should use language that is corresponding to the ocr text, for example, if the ocr text is in Chinese, the corrected text should also be in Chinese.

Finally, please output the corrected Markdown text in a code block.

Example:
```
# Title
This is a list:
- Item 1
- Item 2
```"""


OCR_FIX_TO_JSON_PROMPT = """Please correct the following OCR-recognized text and output the result in JSON format:
```
{ocr_text}
```

User-enforced JSON Format:
```
{enforced_json_format}
```
When making corrections, please adhere to these guidelines:
1. Correct misrecognized words and phrases to improve readability and comprehension
2. Maintain the original paragraph structure and line breaks
3. Identify and extract key information such as titles, headings, lists, names, dates, and numbers
4. Remove irrelevant characters, symbols, and garbled text introduced by OCR recognition errors
5. If user-enforced JSON format is provided, ensure that the corrected text is formatted accordingly
6. You should use language that is corresponding to the ocr text, for example, if the ocr text is in Chinese, the corrected text should also be in Chinese.

Finally, please output the corrected JSON text in a code block.

Example:
```
{{
  "key": "value",
  "key2": "value2"
}}
```"""

EXTRACT_MARKDOWN_PROMPT = """Please analyze the provided image and extract the content in Markdown format. The image will contain text, headings, lists, tables, and possibly code snippets.
When extracting the content, please adhere to the following guidelines:
1. Identify and extract text, preserving the original formatting and structure as much as possible
2. Detect and properly format headings (H1, H2, H3, etc.) using Markdown syntax
3. Recognize and format lists (ordered and unordered) using Markdown syntax
4. Identify and format tables using Markdown syntax, preserving the table structure and content
5. Detect and format any code snippets using Markdown code blocks, preserving the code's syntax and indentation
6. If the image contains any inline images or diagrams, describe them using alt text in Markdown format
7. Preserve the original line breaks and paragraph structure to maintain readability

Finally, please output the extracted content in Markdown format within a code block.

Example:
```
# Title
This is a list:
- Item 1
- Item 2
```"""

EXTRACT_JSON_PROMPT = """Please analyze the image and extract the content in JSON format. The image may contain structured data, key-value pairs, lists, or other JSON-compatible content.
When extracting the content, please adhere to the following guidelines:
1. Identify and extract structured data, key-value pairs, lists, or other JSON-compatible content
2. Maintain the original structure and hierarchy of the extracted data
3. Correct any misrecognized words or phrases to ensure the extracted JSON is accurate
4. Remove any irrelevant characters, symbols, or garbled text introduced by OCR recognition errors
5. If the image contains nested data structures, represent them accurately in the extracted JSON format
6. You should use language that is corresponding to the ocr text, for example, if the ocr text is in English, the extracted JSON should also be in English.

Finally, please output the extracted content in JSON format within a code block.

Example:
```
{{
  "key": "value",
  "key2": "value2"
}}
```"""


# 对于很长的文本来说，我们会将长文本拆成许多短文本，但是文章整体的目录等级信息可能会丢失，因此可以先提取目录信息，然后再提取正文信息
# EXTRACT_MARKDOWN_TOC_LEVEL_PROMPT = """You are required to extract the table of contents (TOC) levels from the provided Markdown content.
