name: Check Code

on:
    push:
        branches:
            - main
            - develop
            - feature/*
    pull_request:
        branches:
            - main
            - develop

jobs:
    check-code:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                  python-version: "3.10"

            - name: Install conda
              uses: goanpeca/setup-miniconda@v2
              with:
                  auto-update-conda: true
                  python-version: "3.10"

            - name: Create conda environment
              run: conda create -n e2m python=3.10 -y

            - name: Activate conda environment
              run: conda activate e2m
              shell: bash -l {0}

            - name: Install dependencies
              run: |
                  conda activate e2m
                  python -m pip install -r requirements.txt

            - name: Start Flask app
              run: |
                  conda activate e2m
                  cd app
                  flask run --host 0.0.0.0 --port=8765 &
              shell: bash -l {0}

            - name: Wait for server to start
              run: sleep 10

            - name: Check API availability
              run: |
                  response=$(curl --write-out '%{http_code}' --silent --output /dev/null http://127.0.0.1:8765/api/v1/ping)
                  if [ $response -ne 200 ]; then
                    echo "API is not available"
                    exit 1
                  else
                    echo "API is available"
                  fi
